export const SET_URL = 'SET_URL';
export const SET_URL_COMP = 'SET_URL_COMP';
export const SET_IS_PARSE_ERROR = 'SET_IS_PARSE_ERROR';
export const SET_CURRENT_TAB_INFO = 'SET_CURRENT_TAB_INFO';
export const SET_USAGE_STATISTIC_ALL = 'SET_USAGE_STATISTIC_ALL';
export const SET_USAGE_STATISTIC_ONE = 'SET_USAGE_STATISTIC_ONE';
